/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kr.hhplus.be.server.api;

import kr.hhplus.be.server.api.model.AssetResult;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RestController;

@Validated

@RestController
public interface AssetApi {

    /**
     * POST /asset/charge/{id}/{amount} : 자산을 충전함.
     *
     * @param id     자산을충전할 user의 아이디 (required)
     * @param amount 충전할 자산의 양 (required)
     * @return 자산충전 성공한 유저의 총자산 양 (status code 200)
     * or unexpected error (status code 400)
     */

    @PostMapping(
            value = "/asset/charge/{id}/{amount}",
            produces = {"application/json"}
    )
    ResponseEntity<AssetResult> chargeAssetByUser(@PathVariable("id") Long id, @PathVariable("amount") Long amount);


    /**
     * GET /asset/{id} : 유저의 자산을 조회함.
     *
     * @param id 자산을조회할 user의 아이디 (required)
     * @return 유저의 총자산 양 (status code 200)
     * or unexpected error (status code 400)
     */

    @GetMapping(
            value = "/asset/{id}",
            produces = {"application/json"}
    )
    ResponseEntity<AssetResult> searchAssetByUser(@PathVariable("id") Long id);

}