/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package kr.hhplus.be.server.api;

import kr.hhplus.be.server.api.model.UserResult;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RestController;

@Validated

@RestController
public interface UserApi {

    /**
     * POST /user/regist/{name} : 새로운 유저정보 등록.
     *
     * @param name 새로 등록할 user의 이름 (required)
     * @return 등록완료된 user정보 (status code 200)
     * or unexpected error (status code 400)
     */

    @PostMapping(
            value = "/user/regist/{name}",
            produces = {"application/json"}
    )
    ResponseEntity<UserResult> registUser(@PathVariable("name") String name);

}